--[[
fl26caps -- runtime patch applier (hdr127 set).

Capacity patch.  It does NOT move the standings object or change its size: 0x39a8f0 is an
offset into the object, with another member at +0x39a9f0, so the boundary is held fixed and
the extra header entries are paid for out of phase tables.

Set:     hdr127
Summary: season header 100 -> 127 competitions, phase tables 600 -> 599, 29 patches

A season holds exactly 100 competition instances.  Past that the surplus is dropped without
a word: the leagues that miss out never get a row for the new season and keep accumulating
into the previous one, which is how a league table comes to show 76 matches played -- two
seasons of 38 -- and about 130 points.

    entries   header bytes   phase tables that still fit
       100        0x4650              600
       127        0x594c              599

1 phase table is the entire price.  127 is the ceiling of this cheap version: every
bound is `cmp r32, 0x64` with an 8-bit immediate, and 0x7f is the largest value that still
fits in a signed byte.  Above that each of the thirteen bounds needs `81 /7 id`, which is
longer than the instruction it replaces and so needs a trampoline per site.

Generated by tools/hdr127.py, which disassembles every site and locates each immediate by
structure rather than by searching for bytes that might belong to a displacement.

Install:
  1. copy this file to <game>\SiderAddons\modules\fl26hdr127.lua
  2. add to sider.ini, in the lua.module list:   lua.module = "fl26hdr127.lua"
  3. start the game and read sider.log

Start a NEW Master League season after installing.  A season already on disk was built
against the 100-entry layout.

The exe has no ASLR (DllCharacteristics 0x8120), so the addresses are absolute and stable.
The applier checks that anyway by verifying the bytes.
--]]

local m = {}

local patches = {
  {va=0x14158f71e, old="64", new="7f",
   why="header bound: cmp ecx, 0x64 -> 127 entries"},
  {va=0x14158f73e, old="64", new="7f",
   why="header bound: cmp ebp, 0x64 -> 127 entries"},
  {va=0x14158f763, old="64", new="7f",
   why="header bound: cmp r8d, 0x64 -> 127 entries"},
  {va=0x14158f78e, old="64", new="7f",
   why="header bound: cmp ecx, 0x64 -> 127 entries"},
  {va=0x14158f7ae, old="64", new="7f",
   why="header bound: cmp ecx, 0x64 -> 127 entries"},
  {va=0x141590491, old="64", new="7f",
   why="header bound: cmp r8d, 0x64 -> 127 entries"},
  {va=0x1415904c1, old="64", new="7f",
   why="header bound: cmp r8d, 0x64 -> 127 entries"},
  {va=0x14159ec1f, old="64", new="7f",
   why="header bound: cmp edx, 0x64 -> 127 entries"},
  {va=0x14159ec4f, old="64", new="7f",
   why="header bound: cmp edx, 0x64 -> 127 entries"},
  {va=0x14159ecff, old="64", new="7f",
   why="header bound: cmp edx, 0x64 -> 127 entries"},
  {va=0x14159ed3f, old="64", new="7f",
   why="header bound: cmp ecx, 0x64 -> 127 entries"},
  {va=0x14159ee73, old="64", new="7f",
   why="header bound: cmp r8d, 0x64 -> 127 entries"},
  {va=0x14159ee93, old="64", new="7f",
   why="header bound: cmp edx, 0x64 -> 127 entries"},
  {va=0x1414fd4e5, old="64000000", new="7f000000",
   why="header initialiser count: mov r9d, 0x64 -> 127 entries stamped with the free sentinel"},
  {va=0x1414fd472, old="50460000", new="4c590000",
   why="phase tables start 0x4650 -> 0x594c  (lea ebx, [rcx + 0x4650])"},
  {va=0x14158df94, old="50460000", new="4c590000",
   why="phase tables start 0x4650 -> 0x594c  (lea eax, [rdx + 0x4650])"},
  {va=0x14158f39d, old="50460000", new="4c590000",
   why="phase tables start 0x4650 -> 0x594c  (mov eax, 0x4650)"},
  {va=0x14158f8e3, old="50460000", new="4c590000",
   why="phase tables start 0x4650 -> 0x594c  (lea ebx, [rsi + 0x4650])"},
  {va=0x14158fe4f, old="50460000", new="4c590000",
   why="phase tables start 0x4650 -> 0x594c  (lea ebx, [rcx + 0x4650])"},
  {va=0x14159026e, old="50460000", new="4c590000",
   why="phase tables start 0x4650 -> 0x594c  (add edi, 0x4650)"},
  {va=0x1413fb202, old="58020000", new="57020000",
   why="phase table count 600 -> 599  (mov ebp, 0x258)"},
  {va=0x1414fd477, old="58020000", new="57020000",
   why="phase table count 600 -> 599  (mov edi, 0x258)"},
  {va=0x14158df84, old="58020000", new="57020000",
   why="phase table count 600 -> 599  (cmp eax, 0x258)"},
  {va=0x14158f383, old="58020000", new="57020000",
   why="phase table count 600 -> 599  (cmp ebx, 0x258)"},
  {va=0x14158f3b2, old="58020000", new="57020000",
   why="phase table count 600 -> 599  (cmp ebx, 0x258)"},
  {va=0x14158f8d3, old="58020000", new="57020000",
   why="phase table count 600 -> 599  (cmp eax, 0x258)"},
  {va=0x14158fe3b, old="58020000", new="57020000",
   why="phase table count 600 -> 599  (cmp esi, 0x258)"},
  {va=0x141590256, old="58020000", new="57020000",
   why="phase table count 600 -> 599  (cmp edi, 0x258)"},
  {va=0x14159edb5, old="58020000", new="57020000",
   why="phase table count 600 -> 599  (cmp ecx, 0x258)"},
}

local function unhex(s)
  local out = {}
  for i = 1, #s, 2 do
    out[#out + 1] = string.char(tonumber(string.sub(s, i, i + 1), 16))
  end
  return table.concat(out)
end

local function tohex(s)
  if s == nil then return "nil" end
  local out = {}
  for i = 1, #s do
    out[#out + 1] = string.format("%02x", string.byte(s, i))
  end
  return table.concat(out)
end

function m.init(ctx)
  local n = #patches
  log(string.format("fl26caps: set '%s', %d patches, verifying", "hdr127", n))

  -- pass 1: read only.  Nothing is written until every site has been confirmed.
  local bad = 0
  for i = 1, n do
    local p = patches[i]
    local want = unhex(p.old)
    local cur = memory.read(p.va, #want)
    if cur ~= want then
      log(string.format("fl26caps: MISMATCH at 0x%x: found %s, expected %s  [%s]",
                        p.va, tohex(cur), p.old, p.why))
      bad = bad + 1
    end
  end
  if bad > 0 then
    log(string.format("fl26caps: ABORTED, %d of %d sites did not match. "
                      .. "Nothing was written; the game is unmodified. "
                      .. "If site 1 is the mismatch, another module has taken that padding.",
                      bad, n))
    return
  end

  -- pass 2: write, then read back, because a write into the code section can silently fail
  -- if the page is not writable for us.  The trampoline goes first, so the jump target
  -- exists before the jump does.
  local written, failed = 0, 0
  for i = 1, n do
    local p = patches[i]
    local new = unhex(p.new)
    memory.write(p.va, new)
    local back = memory.read(p.va, #new)
    if back == new then
      written = written + 1
      log(string.format("fl26caps: [%d/%d] 0x%x %s -> %s  %s",
                        i, n, p.va, p.old, p.new, p.why))
    else
      failed = failed + 1
      log(string.format("fl26caps: WRITE FAILED at 0x%x (%s) -- read back %s",
                        p.va, p.why, tohex(back)))
    end
  end

  if failed == 0 then
    log(string.format("fl26caps: applied all %d patches -- %s", written,
                      "hdr127: season header widened to 127 competitions, 599 phase tables"))
  else
    log(string.format("fl26caps: PARTIAL: %d written, %d failed. The game is now in an "
                      .. "inconsistent state -- quit and report the addresses above.",
                      written, failed))
  end
end

return m
