--[[
fl26caps -- runtime patch applier (hdr192 set).

Capacity patch.  It does NOT move the standings object or change its size: 0x39a8f0 is an
offset into the object, with another member at +0x39a9f0, so the boundary is held fixed and
the extra header entries are paid for out of phase tables.

Set:     hdr192
Summary: season header 100 -> 192 competitions, phase tables 600 -> 597, 42 patches

A season holds exactly 100 competition instances.  Past that the surplus is dropped without
a word: the leagues that miss out never get a row for the new season and keep accumulating
into the previous one, which is how a league table comes to show 76 matches played -- two
seasons of 38 -- and about 130 points.

    entries   header bytes   phase tables that still fit
       100        0x4650              600
       192        0x8700              597

3 phase tables are the entire price.

192 does not fit in the 8-bit immediate the thirteen bounds use, so each
`cmp r32, 0x64` / `jb rel8` pair -- five bytes, six with a REX prefix, which is
exactly what a `jmp rel32` needs -- is redirected to a stub holding the widened
compare, the same branch as a `rel32`, and a jump back.  The stubs live at
0x14252ea20, in the tail of the code section's last page: executable at runtime,
absent from the file, and read as zero before anything is written, so if
another module has taken it the whole set aborts untouched.

Generated by tools/hdr127.py, which disassembles every site and locates each immediate by
structure rather than by searching for bytes that might belong to a displacement.

Install:
  1. copy this file to <game>\SiderAddons\modules\fl26hdr192.lua
  2. add to sider.ini, in the lua.module list:   lua.module = "fl26hdr192.lua"
  3. start the game and read sider.log

Start a NEW Master League season after installing.  A season already on disk was built
against the 100-entry layout.

The exe has no ASLR (DllCharacteristics 0x8120), so the addresses are absolute and stable.
The applier checks that anyway by verifying the bytes.
--]]

local m = {}

local patches = {
  {va=0x14252ea20, old="0000000000000000000000000000000000", new="81f9c00000000f82e40c06ffe9f00c06ff",
   why="header bound trampoline for 0x14158f71c: cmp ecx, 192; jb 0x14158f710; jmp back to 0x14158f721"},
  {va=0x14252ea34, old="0000000000000000000000000000000000", new="81fdc00000000f82060d06ffe9fc0c06ff",
   why="header bound trampoline for 0x14158f73c: cmp ebp, 192; jb 0x14158f746; jmp back to 0x14158f741"},
  {va=0x14252ea48, old="000000000000000000000000000000000000", new="4181f8c00000000f82f10c06ffe90c0d06ff",
   why="header bound trampoline for 0x14158f760: cmp r8d, 192; jb 0x14158f746; jmp back to 0x14158f766"},
  {va=0x14252ea5c, old="0000000000000000000000000000000000", new="81f9c00000000f82180d06ffe9240d06ff",
   why="header bound trampoline for 0x14158f78c: cmp ecx, 192; jb 0x14158f780; jmp back to 0x14158f791"},
  {va=0x14252ea70, old="0000000000000000000000000000000000", new="81f9c00000000f82240d06ffe9300d06ff",
   why="header bound trampoline for 0x14158f7ac: cmp ecx, 192; jb 0x14158f7a0; jmp back to 0x14158f7b1"},
  {va=0x14252ea84, old="000000000000000000000000000000000000", new="4181f8c00000000f82ef1906ffe9fe1906ff",
   why="header bound trampoline for 0x14159048e: cmp r8d, 192; jb 0x141590480; jmp back to 0x141590494"},
  {va=0x14252ea98, old="000000000000000000000000000000000000", new="4181f8c00000000f820b1a06ffe91a1a06ff",
   why="header bound trampoline for 0x1415904be: cmp r8d, 192; jb 0x1415904b0; jmp back to 0x1415904c4"},
  {va=0x14252eaac, old="0000000000000000000000000000000000", new="81fac00000000f82580107ffe9650107ff",
   why="header bound trampoline for 0x14159ec1d: cmp edx, 192; jb 0x14159ec10; jmp back to 0x14159ec22"},
  {va=0x14252eac0, old="0000000000000000000000000000000000", new="81fac00000000f82740107ffe9810107ff",
   why="header bound trampoline for 0x14159ec4d: cmp edx, 192; jb 0x14159ec40; jmp back to 0x14159ec52"},
  {va=0x14252ead4, old="0000000000000000000000000000000000", new="81fac00000000f82100207ffe91d0207ff",
   why="header bound trampoline for 0x14159ecfd: cmp edx, 192; jb 0x14159ecf0; jmp back to 0x14159ed02"},
  {va=0x14252eae8, old="0000000000000000000000000000000000", new="81f9c00000000f823c0207ffe9490207ff",
   why="header bound trampoline for 0x14159ed3d: cmp ecx, 192; jb 0x14159ed30; jmp back to 0x14159ed42"},
  {va=0x14252eafc, old="000000000000000000000000000000000000", new="4181f8c00000000f82590307ffe9680307ff",
   why="header bound trampoline for 0x14159ee70: cmp r8d, 192; jb 0x14159ee62; jmp back to 0x14159ee76"},
  {va=0x14252eb10, old="0000000000000000000000000000000000", new="81fac00000000f82680307ffe9750307ff",
   why="header bound trampoline for 0x14159ee91: cmp edx, 192; jb 0x14159ee84; jmp back to 0x14159ee96"},
  {va=0x14158f71c, old="83f96472ef", new="e9fff2f900",
   why="header bound: cmp ecx, 0x64 / jb -> the trampoline at 0x14252ea20 (jmp rel32)"},
  {va=0x14158f73c, old="83fd647205", new="e9f3f2f900",
   why="header bound: cmp ebp, 0x64 / jb -> the trampoline at 0x14252ea34 (jmp rel32)"},
  {va=0x14158f760, old="4183f86472e0", new="e9e3f2f90090",
   why="header bound: cmp r8d, 0x64 / jb -> the trampoline at 0x14252ea48 (jmp rel32 + nop)"},
  {va=0x14158f78c, old="83f96472ef", new="e9cbf2f900",
   why="header bound: cmp ecx, 0x64 / jb -> the trampoline at 0x14252ea5c (jmp rel32)"},
  {va=0x14158f7ac, old="83f96472ef", new="e9bff2f900",
   why="header bound: cmp ecx, 0x64 / jb -> the trampoline at 0x14252ea70 (jmp rel32)"},
  {va=0x14159048e, old="4183f86472ec", new="e9f1e5f90090",
   why="header bound: cmp r8d, 0x64 / jb -> the trampoline at 0x14252ea84 (jmp rel32 + nop)"},
  {va=0x1415904be, old="4183f86472ec", new="e9d5e5f90090",
   why="header bound: cmp r8d, 0x64 / jb -> the trampoline at 0x14252ea98 (jmp rel32 + nop)"},
  {va=0x14159ec1d, old="83fa6472ee", new="e98afef800",
   why="header bound: cmp edx, 0x64 / jb -> the trampoline at 0x14252eaac (jmp rel32)"},
  {va=0x14159ec4d, old="83fa6472ee", new="e96efef800",
   why="header bound: cmp edx, 0x64 / jb -> the trampoline at 0x14252eac0 (jmp rel32)"},
  {va=0x14159ecfd, old="83fa6472ee", new="e9d2fdf800",
   why="header bound: cmp edx, 0x64 / jb -> the trampoline at 0x14252ead4 (jmp rel32)"},
  {va=0x14159ed3d, old="83f96472ee", new="e9a6fdf800",
   why="header bound: cmp ecx, 0x64 / jb -> the trampoline at 0x14252eae8 (jmp rel32)"},
  {va=0x14159ee70, old="4183f86472ec", new="e987fcf80090",
   why="header bound: cmp r8d, 0x64 / jb -> the trampoline at 0x14252eafc (jmp rel32 + nop)"},
  {va=0x14159ee91, old="83fa6472ee", new="e97afcf800",
   why="header bound: cmp edx, 0x64 / jb -> the trampoline at 0x14252eb10 (jmp rel32)"},
  {va=0x1414fd4e5, old="64000000", new="c0000000",
   why="header initialiser count: mov r9d, 0x64 -> 192 entries stamped with the free sentinel"},
  {va=0x1414fd472, old="50460000", new="00870000",
   why="phase tables start 0x4650 -> 0x8700  (lea ebx, [rcx + 0x4650])"},
  {va=0x14158df94, old="50460000", new="00870000",
   why="phase tables start 0x4650 -> 0x8700  (lea eax, [rdx + 0x4650])"},
  {va=0x14158f39d, old="50460000", new="00870000",
   why="phase tables start 0x4650 -> 0x8700  (mov eax, 0x4650)"},
  {va=0x14158f8e3, old="50460000", new="00870000",
   why="phase tables start 0x4650 -> 0x8700  (lea ebx, [rsi + 0x4650])"},
  {va=0x14158fe4f, old="50460000", new="00870000",
   why="phase tables start 0x4650 -> 0x8700  (lea ebx, [rcx + 0x4650])"},
  {va=0x14159026e, old="50460000", new="00870000",
   why="phase tables start 0x4650 -> 0x8700  (add edi, 0x4650)"},
  {va=0x1413fb202, old="58020000", new="55020000",
   why="phase table count 600 -> 597  (mov ebp, 0x258)"},
  {va=0x1414fd477, old="58020000", new="55020000",
   why="phase table count 600 -> 597  (mov edi, 0x258)"},
  {va=0x14158df84, old="58020000", new="55020000",
   why="phase table count 600 -> 597  (cmp eax, 0x258)"},
  {va=0x14158f383, old="58020000", new="55020000",
   why="phase table count 600 -> 597  (cmp ebx, 0x258)"},
  {va=0x14158f3b2, old="58020000", new="55020000",
   why="phase table count 600 -> 597  (cmp ebx, 0x258)"},
  {va=0x14158f8d3, old="58020000", new="55020000",
   why="phase table count 600 -> 597  (cmp eax, 0x258)"},
  {va=0x14158fe3b, old="58020000", new="55020000",
   why="phase table count 600 -> 597  (cmp esi, 0x258)"},
  {va=0x141590256, old="58020000", new="55020000",
   why="phase table count 600 -> 597  (cmp edi, 0x258)"},
  {va=0x14159edb5, old="58020000", new="55020000",
   why="phase table count 600 -> 597  (cmp ecx, 0x258)"},
}

local function unhex(s)
  local out = {}
  for i = 1, #s, 2 do
    out[#out + 1] = string.char(tonumber(string.sub(s, i, i + 1), 16))
  end
  return table.concat(out)
end

local function tohex(s)
  if s == nil then return "nil" end
  local out = {}
  for i = 1, #s do
    out[#out + 1] = string.format("%02x", string.byte(s, i))
  end
  return table.concat(out)
end

function m.init(ctx)
  local n = #patches
  log(string.format("fl26caps: set '%s', %d patches, verifying", "hdr192", n))

  -- pass 1: read only.  Nothing is written until every site has been confirmed.
  local bad = 0
  for i = 1, n do
    local p = patches[i]
    local want = unhex(p.old)
    local cur = memory.read(p.va, #want)
    if cur ~= want then
      log(string.format("fl26caps: MISMATCH at 0x%x: found %s, expected %s  [%s]",
                        p.va, tohex(cur), p.old, p.why))
      bad = bad + 1
    end
  end
  if bad > 0 then
    log(string.format("fl26caps: ABORTED, %d of %d sites did not match. "
                      .. "Nothing was written; the game is unmodified. "
                      .. "If site 1 is the mismatch, another module has taken that padding.",
                      bad, n))
    return
  end

  -- pass 2: write, then read back, because a write into the code section can silently fail
  -- if the page is not writable for us.  The trampoline goes first, so the jump target
  -- exists before the jump does.
  local written, failed = 0, 0
  for i = 1, n do
    local p = patches[i]
    local new = unhex(p.new)
    memory.write(p.va, new)
    local back = memory.read(p.va, #new)
    if back == new then
      written = written + 1
      log(string.format("fl26caps: [%d/%d] 0x%x %s -> %s  %s",
                        i, n, p.va, p.old, p.new, p.why))
    else
      failed = failed + 1
      log(string.format("fl26caps: WRITE FAILED at 0x%x (%s) -- read back %s",
                        p.va, p.why, tohex(back)))
    end
  end

  if failed == 0 then
    log(string.format("fl26caps: applied all %d patches -- %s", written,
                      "hdr192: season header widened to 192 competitions, 597 phase tables"))
  else
    log(string.format("fl26caps: PARTIAL: %d written, %d failed. The game is now in an "
                      .. "inconsistent state -- quit and report the addresses above.",
                      written, failed))
  end
end

return m
