--[[
fl26rank -- give the league rank one more bit, so a national pyramid can be more than three
deep.

Why: every regulation record carries a rank -- first division, second, third -- and the game
keeps it in the TOP TWO BITS of the flags word at +0x304. Two bits count to three. We have
added fourth and fifth divisions, so our D3, D4 and D5 all end up carrying the value 3, and
the UI that pairs a league with the one above and below it then cannot tell them apart: Ligue
2 shows no lower league at all (that panel only computes one for rank 1), and France D4 shows
itself as its own lower league.

What this does: moves the rank down one bit, to bits 29-31, so it counts to seven. Bit 29 is
today the top bit of the group count (bits 24-29), and the loader masks that count to five
bits before storing it (0x1414f828d: movzx edx, byte [rax+0x10]; and dl,0x1f), so nothing
shipped ever sets bit 29. The group count keeps bits 24-28, which is still up to 31 groups --
more than the data file can even express.

Every instruction involved re-encodes to the same length, so this is an in-place byte patch:
no trampolines, no extra memory, nothing relocated.

  rank read    shr/sar r, 0x1e            -> 0x1d
               and/test r, 0xc0000000     -> 0xe0000000
               cmp r, 0x40000000 / 0x80000000 / 0xc0000000 -> 0x20000000 / 0x40000000 / 0x60000000
               and r, 0x3fffffff          -> 0x1fffffff   (record copier: "everything but the rank")
  rank write   0x1414c9cc0 mask, 0x1414c9ccd shl
  group read   and r, 0x3f -> 0x1f after shr r,0x18;  and r, 0x3f000000 -> 0x1f000000
  group write  0x1414c9e70 mask, 0x1414c9e7d and

The sites were found by walking every reference to +0x304 in .trace, decoding the instruction
whose displacement lands exactly there, and following the register the value went into -- an
idiom counts only when it acts on that register, because a compare against 0x40000000 near a
read proves nothing on its own.

The word is also reached through its top byte. +0x307 is bits 24-31 of the same word, so in
that byte the group count is the low six bits and the rank is the top two; ten places read it
that way (test byte [reg+0x307], 0x3f, or movzx then and r,0x3f). Those masks take six bits,
so once a league carries rank 4 or higher -- which sets bit 29 -- an unnarrowed read there
returns 32 plus the real group count, and that number is used as a loop bound. The same walk
is therefore run a second time over the displacement 0x307, with the byte-sized forms of the
same idioms (shr r,6 for the rank, and/test 0x3f -> 0x1f for the count).

Three sites around 0x1422b9xxx that match the idiom by eye were excluded by hand: their
structure has a +0xb98 field, so it is not a regulation record.
Generated by tools/mkrankpatch.py; do not edit the table by hand.

All-or-nothing: every old byte sequence is verified first, and if a single one differs nothing
at all is written and the game runs unmodified.

After this, a league's rank comes from the data file exactly as before -- Regulation row +0x10
bits 15-17 -- except that the value may now be 4 or 5 as well. The loader already passes three
bits (0x1414f82a8: shr edx,0xf; and dl,7); only the setter was throwing the third one away.
--]]

local m = {}

-- {va, expected bytes now, bytes to write, what it is}
local PATCHES = {
  {va=0x140a9b750, old="f680070300003f", new="f680070300001f", why="group-read: test byte ptr [rax + 0x307], 0x3f -- byte +0x307, six bits"},
  {va=0x140a9b76e, old="83e13f", new="83e11f", why="group-read: and ecx, 0x3f -- byte +0x307, six bits"},
  {va=0x140a9b7e8, old="4183e13f", new="4183e11f", why="group-read: and r9d, 0x3f"},
  {va=0x140a9b84b, old="4183e13f", new="4183e11f", why="group-read: and r9d, 0x3f"},
  {va=0x140a9b88d, old="4183e13f", new="4183e11f", why="group-read: and r9d, 0x3f"},
  {va=0x140a9b8fa, old="83e13f", new="83e11f", why="group-read: and ecx, 0x3f"},
  {va=0x140a9b993, old="83e13f", new="83e11f", why="group-read: and ecx, 0x3f"},
  {va=0x140a9b9df, old="4183e13f", new="4183e11f", why="group-read: and r9d, 0x3f"},
  {va=0x140a9ba52, old="4183e13f", new="4183e11f", why="group-read: and r9d, 0x3f"},
  {va=0x140a9baab, old="4183e13f", new="4183e11f", why="group-read: and r9d, 0x3f"},
  {va=0x140a9d2cd, old="83e33f", new="83e31f", why="group-read: and ebx, 0x3f"},
  {va=0x140aee421, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x140aee426, old="3d00000080", new="3d00000040", why="rank-read: cmp eax, 0x80000000"},
  {va=0x140ec2587, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x140ec258d, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x140ec261b, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x140ec2621, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x140edc0fe, old="c1ef1e", new="c1ef1d", why="rank-read: shr edi, 0x1e"},
  {va=0x140edc21e, old="c1ed1e", new="c1ed1d", why="rank-read: shr ebp, 0x1e"},
  {va=0x140edc334, old="c1ed1e", new="c1ed1d", why="rank-read: shr ebp, 0x1e"},
  {va=0x140edc424, old="c1ef1e", new="c1ef1d", why="rank-read: shr edi, 0x1e"},
  {va=0x140edc514, old="c1ee1e", new="c1ee1d", why="rank-read: shr esi, 0x1e"},
  {va=0x140edc600, old="c1e91e", new="c1e91d", why="rank-read: shr ecx, 0x1e"},
  {va=0x140edc736, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x140edc73b, old="3d00000040", new="3d00000020", why="rank-read: cmp eax, 0x40000000"},
  {va=0x140edc85e, old="c1eb1e", new="c1eb1d", why="rank-read: shr ebx, 0x1e"},
  {va=0x140edc9f0, old="c1e91e", new="c1e91d", why="rank-read: shr ecx, 0x1e"},
  {va=0x140edcb7f, old="c1e91e", new="c1e91d", why="rank-read: shr ecx, 0x1e"},
  {va=0x140edcd64, old="c1ee1e", new="c1ee1d", why="rank-read: shr esi, 0x1e"},
  {va=0x140edce4c, old="c1ed1e", new="c1ed1d", why="rank-read: shr ebp, 0x1e"},
  {va=0x140edcf6d, old="41c1ee1e", new="41c1ee1d", why="rank-read: shr r14d, 0x1e"},
  {va=0x140edd07a, old="c1ed1e", new="c1ed1d", why="rank-read: shr ebp, 0x1e"},
  {va=0x140edd19e, old="c1ee1e", new="c1ee1d", why="rank-read: shr esi, 0x1e"},
  {va=0x140edd2dc, old="41c1ef1e", new="41c1ef1d", why="rank-read: shr r15d, 0x1e"},
  {va=0x140edd4a6, old="41c1ee1e", new="41c1ee1d", why="rank-read: shr r14d, 0x1e"},
  {va=0x140edd5f2, old="c1e91e", new="c1e91d", why="rank-read: shr ecx, 0x1e"},
  {va=0x140edd736, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x140edd73b, old="3d00000040", new="3d00000020", why="rank-read: cmp eax, 0x40000000"},
  {va=0x140edd88b, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x140edd890, old="3d00000040", new="3d00000020", why="rank-read: cmp eax, 0x40000000"},
  {va=0x140edda82, old="c1e91e", new="c1e91d", why="rank-read: shr ecx, 0x1e"},
  {va=0x140fa14d0, old="c1e81e", new="c1e81d", why="rank-read: shr eax, 0x1e"},
  {va=0x140fb63af, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x140fb63b5, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x140fc7340, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x140fc7346, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x141261fb6, old="81e10000003f", new="81e10000001f", why="group-read: and ecx, 0x3f000000"},
  {va=0x141261fcc, old="81e1ffffff3f", new="81e1ffffff1f", why="rank-read: and ecx, 0x3fffffff -- copier: all but the rank"},
  {va=0x1412623f6, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x1412623fc, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x1412739ae, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x1412739b4, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14127d9a9, old="c1e91e", new="c1e91d", why="rank-read: shr ecx, 0x1e"},
  {va=0x1412a4dc2, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x1412a4dc8, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x1412a7e6b, old="c1e81e", new="c1e81d", why="rank-read: shr eax, 0x1e"},
  {va=0x1412a97c2, old="c1e91e", new="c1e91d", why="rank-read: shr ecx, 0x1e"},
  {va=0x14131f5ec, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14131f5f2, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14131fba1, old="c1eb1e", new="c1eb1d", why="rank-read: shr ebx, 0x1e"},
  {va=0x141321b7b, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x141321b80, old="3d00000040", new="3d00000020", why="rank-read: cmp eax, 0x40000000"},
  {va=0x141322917, old="41c1ef1e", new="41c1ef1d", why="rank-read: shr r15d, 0x1e"},
  {va=0x141354171, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x141354177, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x141356332, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14135633c, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x141358d60, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x141358d6a, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x141359e7f, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x141359e85, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x141361ced, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x141361cf3, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x1413b79cf, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x1413b79d5, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x1414c9cc0, old="81a104030000ffffff3f", new="81a104030000ffffff1f", why="rank-write: and dword ptr [rcx + 0x304], 0x3fffffff -- rank setter, keep 29 bits"},
  {va=0x1414c9ccd, old="c1e01e", new="c1e01d", why="rank-write: shl eax, 0x1e -- rank setter, three bits now"},
  {va=0x1414c9e70, old="81a104030000ffffffc0", new="81a104030000ffffffe0", why="group-write: and dword ptr [rcx + 0x304], 0xc0ffffff -- group setter, keep bit 29"},
  {va=0x1414c9e7d, old="83e03f", new="83e01f", why="group-write: and eax, 0x3f -- group setter, five bits now"},
  {va=0x1414ef2d6, old="81e10000003f", new="81e10000001f", why="group-read: and ecx, 0x3f000000"},
  {va=0x1414ef2ee, old="25ffffff3f", new="25ffffff1f", why="rank-read: and eax, 0x3fffffff -- copier: all but the rank"},
  {va=0x1415104a8, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x1415104ad, old="3d00000080", new="3d00000040", why="rank-read: cmp eax, 0x80000000"},
  {va=0x1415104dd, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x1415104ec, old="3d00000040", new="3d00000020", why="rank-read: cmp eax, 0x40000000"},
  {va=0x1415105fb, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x141510601, old="81f9000000c0", new="81f900000060", why="rank-read: cmp ecx, 0xc0000000"},
  {va=0x141510612, old="3d00000080", new="3d00000040", why="rank-read: cmp eax, 0x80000000"},
  {va=0x141514256, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x14151425b, old="3d00000080", new="3d00000040", why="rank-read: cmp eax, 0x80000000"},
  {va=0x141514278, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x14151427d, old="3d000000c0", new="3d00000060", why="rank-read: cmp eax, 0xc0000000"},
  {va=0x1415142c9, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x1415142ce, old="3d00000040", new="3d00000020", why="rank-read: cmp eax, 0x40000000"},
  {va=0x1415143e0, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x1415143e6, old="81f9000000c0", new="81f900000060", why="rank-read: cmp ecx, 0xc0000000"},
  {va=0x1415143f7, old="3d00000080", new="3d00000040", why="rank-read: cmp eax, 0x80000000"},
  {va=0x14151a359, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14151a361, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14152d33d, old="4183e73f", new="4183e71f", why="group-read: and r15d, 0x3f -- byte +0x307, six bits"},
  {va=0x141541197, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14154119d, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x141541da5, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x141541dab, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x141541dcb, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x141541dd0, old="3d00000080", new="3d00000040", why="rank-read: cmp eax, 0x80000000"},
  {va=0x141542d13, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x141542d19, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x141543055, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14154305b, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x141543255, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14154325b, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x14154380f, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x141543815, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14154721b, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x141547221, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14154732e, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x141547334, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x141556bb9, old="83e13f", new="83e11f", why="group-read: and ecx, 0x3f -- byte +0x307, six bits"},
  {va=0x14155a6ea, old="4183e03f", new="4183e01f", why="group-read: and r8d, 0x3f -- byte +0x307, six bits"},
  {va=0x14155a83f, old="83e23f", new="83e21f", why="group-read: and edx, 0x3f -- byte +0x307, six bits"},
  {va=0x14155cff6, old="4183e03f", new="4183e01f", why="group-read: and r8d, 0x3f -- byte +0x307, six bits"},
  {va=0x141565e4a, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x141565e4f, old="3d00000080", new="3d00000040", why="rank-read: cmp eax, 0x80000000"},
  {va=0x14159b503, old="83e73f", new="83e71f", why="group-read: and edi, 0x3f -- byte +0x307, six bits"},
  {va=0x14218cf03, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14218cf09, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x14218d051, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14218d057, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14218d223, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14218d229, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14218da44, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14218da4a, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x14218dbd4, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14218dbda, old="81f900000040", new="81f900000020", why="rank-read: cmp ecx, 0x40000000"},
  {va=0x14218f92a, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14218f930, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14218fa9e, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14218faa4, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14218fc58, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14218fc5e, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14218fd68, old="81e1000000c0", new="81e1000000e0", why="rank-read: and ecx, 0xc0000000"},
  {va=0x14218fd6e, old="81f900000080", new="81f900000040", why="rank-read: cmp ecx, 0x80000000"},
  {va=0x14218fec3, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x14218fec8, old="3d00000040", new="3d00000020", why="rank-read: cmp eax, 0x40000000"},
  {va=0x14218fef1, old="25000000c0", new="25000000e0", why="rank-read: and eax, 0xc0000000"},
  {va=0x14218fefb, old="3d00000080", new="3d00000040", why="rank-read: cmp eax, 0x80000000"},
}

local function bin2hex(s)
  return (s:gsub(".", function(c) return string.format("%02x", c:byte()) end))
end

local function hex2bin(h)
  return (h:gsub("%x%x", function(b) return string.char(tonumber(b, 16)) end))
end

function m.init(ctx)
  -- 1. verify every site before touching any of them
  for i, p in ipairs(PATCHES) do
    local got = bin2hex(memory.read(p.va, #p.old / 2))
    if got ~= p.old then
      log(string.format("fl26rank: bytes at 0x%x are %s, expected %s (%s) -- aborting, nothing written",
                        p.va, got, p.old, p.why))
      return
    end
  end

  -- 2. write
  local counts = {}
  for _, p in ipairs(PATCHES) do
    memory.write(p.va, hex2bin(p.new))
    local role = p.why:match("^[^:]+")
    counts[role] = (counts[role] or 0) + 1
  end

  -- 3. read back, so a silently failed write cannot pass for a good one
  local bad = 0
  for _, p in ipairs(PATCHES) do
    if bin2hex(memory.read(p.va, #p.new / 2)) ~= p.new then bad = bad + 1 end
  end
  if bad > 0 then
    log(string.format("fl26rank: %d of %d sites did not take the new bytes", bad, #PATCHES))
    return
  end

  local parts = {}
  for role, n in pairs(counts) do parts[#parts + 1] = string.format("%s %d", role, n) end
  table.sort(parts)
  log(string.format("fl26rank: live -- league rank widened to bits 29-31 (%d sites: %s); " ..
                    "ranks 1-7 now, group count keeps 5 bits", #PATCHES, table.concat(parts, ", ")))
end

return m
